### ISSUE TITLE
Error: linker `cc` not found

### ISSUE THREAD

**Issue by Albonycal** [resyncgg/ripgen#1]
I think `gcc` is also a dependency? 
because installing gcc fixed this 
Thanks

**Comment by d0nutptr** [comment]
Hey! 

If you ever get this when you're trying to compile a rust program it's because you need to have a linker installed. The common way this is done is running the following (if you're on Ubuntu).

```
sudo apt-get update -y && sudo apt-get install -y build-essential
```

Let me know if that helped solve your problem!

**Comment by Albonycal** [comment]
yea I solved it myself, but made an issue because 
this should be added to the readme :)
