### ISSUE TITLE
Request for -f option like dnsgen

### ISSUE THREAD

**Issue by proabiral** [resyncgg/ripgen#11]
DNSgen has an option  (-f / --fast) to generate lower amount of domains with most probable words only. This is very useful when passing large number of subdomains to the tool as the output can be very large without this option.

**Comment by d0nutptr** [comment]
Hey! Thanks for the idea! I'll add it today

**Comment by d0nutptr** [comment]
You can now use `-f` which will do the same thing that dnsgen does (https://github.com/ProjectAnte/dnsgen/blob/16daeef81205e7663708b3ee11d759215c7168fe/dnsgen/dnsgen.py#L220)
