### ISSUE TITLE
error parsing domains with certain special characters,  ('_' . '-'), underscore and minus sign

### ISSUE THREAD

**Issue by r0ckYr** [resyncgg/ripgen#2]
![ripgen-2](https://user-images.githubusercontent.com/73944333/150728802-48e96828-6b9c-4b05-9a22-56f052358054.png)

ERROR : thread 'main' panicked at 'Failed to create Ripgen iterator: ErrorParsingDomain("463103032_uk.pal.dev.site.yahoo.com")', /home/rocky/.cargo/registry/src/github.com-1ecc6299db9ec823/ripgen-0.1.2/src/main.rs:25:7
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by d0nutptr** [comment]
Hey thanks for the report! 

You're totally correct - this was a bug. I updated the code to correctly account for parsing non-standard domain names (those with special, tho accepted characters).

I updated the projects to

`ripgen 0.1.3` 
`ripgen_lib 0.1.1` 

so if you `cargo install ripgen --force` it should download the new, latest version of these libraries with the fix.

Thanks again!
