### ISSUE TITLE
Generating Out of Scope

### ISSUE THREAD

**Issue by jaikishantulswani** [resyncgg/ripgen#4]
Hi @d0nutptr
thank you for this tool, here I am not able to figure out that why it is generating permutations which is out of scope like it is generating permutations on domain which is not supplied, Interesting....
for example:

**wordlist**
`exampe`

**domainlist**
`exampecenter.exampe.com`

so as per the above, it should have to create permutations for domain `exampe.com` but it is also genrating permutations for domain **exampecenter.com** which is not even in the domain list

`ripgen -d domainlist -w wordlist `

**exampecentercenter.exampecenter.com**
exampe.exampe.com
exampecenter.exampe.exampe.com
exampe.exampecenter.exampe.com
exampecenter.exampecenter.exampe.com
exampecenter.exampecenter.exampe.com
exampeexampecenter.exampe.com
exampecenterexampe.exampe.com
exampe-exampecenter.exampe.com
exampecenter-exampe.exampe.com
exampecenterexampecenter.exampe.com
exampecenterexampecenter.exampe.com
exampecenter-exampecenter.exampe.com
exampecenter-exampecenter.exampe.com

Can you please check this.

Thank you.

**Comment by d0nutptr** [comment]
Hey! Thanks for the bug report. 
I'll take a look right away - I have an idea what I might've done wrong :)

**Comment by d0nutptr** [comment]
Okay so the new version of `ripgen_lib` should fix your issue! 

To test this, `cargo install --force ripgen` will reinstall `ripgen` with the new library and bugfix :)

**Comment by jaikishantulswani** [comment]
@d0nutptr Thats fast, thank you :)

**Comment by jaikishantulswani** [comment]
Hi @d0nutptr One more issue I would like to bring to you knowledge. I notice that ripgen is missing some combinations as compare to dnsgen, can I submit this here ?
